version: "3"

services:
  app:
    image: scala-integrationtest-example-app:0.1
    ports:
      - 8080

  database:
    image: postgres:10
    ports:
      - 5432
    healthcheck:
      test: ["CMD", "psql", "-U", "postgres", "-c", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 3